#!/usr/bin/python3
"""Convert QS projects into Python packages that can be parsed with MyPy."""
from pineboolib.application.parsers.parser_qsa import pyconvert

if __name__ == "__main__":
    pyconvert.main()
